import { createElement, useState } from 'react';
import { Ambulance, ArrowRight, Award, CalendarDays, Check, ChevronDown, Clock3, HeartPulse, MessageCircle, Search, ShieldCheck, Stethoscope, UsersRound } from 'lucide-react';
import './index.css';

const specialties = [['Cardiology', 'Heart care led by experienced cardiac specialists'], ['Orthopaedics', 'Advanced bone, joint and spine care'], ['Women & Child', 'Care through every stage of life'], ['Neurology', 'Comprehensive brain and nervous system care'], ['Gastroenterology', 'Digestive health diagnosis and treatment'], ['General Medicine', 'Everyday health and preventive care']];
const faqs = [['How do I book an appointment?', 'Choose a doctor, submit your request, and our care team will confirm a convenient time.'], ['Do you accept cashless insurance?', 'Yes. Our insurance desk supports major cashless providers and guides you through pre-authorisation.'], ['What should I bring for my first visit?', 'Please bring a photo ID, insurance card, previous medical reports and your current prescriptions.']];
export default function Home({ onNavigate }) {
  const [submitted, setSubmitted] = useState(false); const [openFaq, setOpenFaq] = useState(0);
  const submit = (event) => { event.preventDefault(); setSubmitted(true); event.currentTarget.reset(); };
  return <div className="hospital-home">
    <section className="home-hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><ShieldCheck size={16}/> Trusted care. Every day.</p><h1 id="hero-title">Healthcare that feels <em>personal.</em></h1><p className="hero-lede">Clinical excellence, compassionate specialists and seamless care for every member of your family.</p><div className="hero-actions"><button className="primary-button" onClick={() => document.getElementById('appointment').scrollIntoView({ behavior: 'smooth' })}>Book an appointment <ArrowRight size={18}/></button><a className="emergency-button" href="tel:+919876543210"><Ambulance size={18}/> Emergency: Call now</a></div><div className="trust-row"><span><Check/> NABH-aligned care</span><span><Check/> 24/7 emergency</span><span><Check/> Cashless insurance</span></div></div><div className="hero-panel"><div className="availability"><span className="pulse"/> Doctors available today</div><h2>Care when you need it</h2><p>Consult leading specialists in clinic or online.</p><div className="hero-stat-grid"><div><strong>50k+</strong><span>Patients cared for</span></div><div><strong>200+</strong><span>Expert doctors</span></div><div><strong>25+</strong><span>Specialities</span></div><div><strong>24/7</strong><span>Emergency care</span></div></div></div></section>
    <section className="quick-care" aria-label="Quick access"><button onClick={() => onNavigate('find-doctors')}><Search/><span>Find a doctor<small>Choose the right expert</small></span><ArrowRight/></button><a href="tel:+919876543210"><Ambulance/><span>Emergency care<small>Immediate assistance</small></span><ArrowRight/></a><button onClick={() => document.getElementById('appointment').scrollIntoView({ behavior: 'smooth' })}><CalendarDays/><span>Book a visit<small>Request an appointment</small></span><ArrowRight/></button></section>
    <section className="section-block"><div className="section-heading"><p className="eyebrow">WHY AMRUTAM</p><h2>Expert care, thoughtfully delivered.</h2><p>From first consultation to recovery, our teams make every step clear, safe and reassuring.</p></div><div className="benefit-grid">{[[HeartPulse,'Patient-first care','A coordinated care plan built around your health goals.'],[Award,'Clinical excellence','Experienced specialists supported by modern diagnostics.'],[Clock3,'Timely access','Convenient appointments and responsive care, seven days a week.'],[ShieldCheck,'Transparent support','Clear guidance on treatment, estimates and insurance.']].map(([BenefitIcon,title,text])=><article className="benefit-card" key={title}>{createElement(BenefitIcon)}<h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="speciality-section section-block"><div className="section-heading inline-heading"><div><p className="eyebrow">OUR SPECIALITIES</p><h2>Specialised care for every need.</h2></div><button className="link-button" onClick={() => onNavigate('find-doctors')}>Explore doctors <ArrowRight size={17}/></button></div><div className="speciality-grid">{specialties.map(([title,text])=><article className="speciality-card" key={title}><Stethoscope/><h3>{title}</h3><p>{text}</p><button onClick={() => onNavigate('find-doctors')} aria-label={`Find a ${title} doctor`}>Find a specialist <ArrowRight size={15}/></button></article>)}</div></section>
    <section id="appointment" className="appointment-section"><div><p className="eyebrow">APPOINTMENT REQUEST</p><h2>Let’s find the right care for you.</h2><p>Share your details and our patient-care team will call you to confirm your visit.</p><div className="appointment-points"><span><Check/> Same-day slots where available</span><span><Check/> Assistance with insurance and reports</span></div></div><form onSubmit={submit}><label>Full name<input name="name" required minLength="2" placeholder="Your full name" /></label><label>Mobile number<input name="phone" required inputMode="tel" pattern="[0-9+ -]{8,}" placeholder="Your phone number" /></label><label>Preferred speciality<select name="speciality" defaultValue=""><option value="" disabled>Select a speciality</option>{specialties.map(([title])=><option key={title}>{title}</option>)}</select></label><button className="primary-button" type="submit">Request appointment <ArrowRight size={18}/></button>{submitted && <p className="form-success" role="status">Thank you. Our care team will contact you shortly.</p>}</form></section>
    <section className="section-block"><div className="section-heading"><p className="eyebrow">PATIENT STORIES</p><h2>Trusted by families, every day.</h2></div><div className="testimonial-grid"><blockquote>“The team explained every step with such calm and clarity. I felt genuinely cared for.”<footer>— Meera S., Cardiology patient</footer></blockquote><blockquote>“From admission to follow-up, everything was seamless. The nursing team was exceptional.”<footer>— Rajesh K., Orthopaedics patient</footer></blockquote><aside className="insurance-card"><UsersRound/><h3>Insurance support</h3><p>We work with leading insurers for a smoother cashless experience.</p><button>View insurance information <ArrowRight size={15}/></button></aside></div></section>
    <section className="faq-section section-block"><div className="section-heading"><p className="eyebrow">HELP CENTRE</p><h2>Questions, answered.</h2></div>{faqs.map(([question,answer], i)=><div className="faq-item" key={question}><button aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?-1:i)}>{question}<ChevronDown className={openFaq===i?'rotate':''}/></button>{openFaq===i&&<p>{answer}</p>}</div>)}</section>
    <a className="whatsapp-float" href="https://wa.me/919876543210" target="_blank" rel="noreferrer" aria-label="Chat with Amrutam Hospital on WhatsApp"><MessageCircle/></a><a className="mobile-book" href="#appointment">Book appointment</a>
  </div>;
}
